pretrained_model_path: "/mnt/disk_1/dongxin/checkpoints/stable-diffusion-v1-5"
output_dir: "/mnt/disk_1/dongxin/FollowYourPose/output"


validation_data:
  prompts:
#    - "A Iron man on the beach"
    - "Monkeys on the sea"
#    - "Batman on the street"
    - "Stormtroopers on the moon"
    - "astronauts in the desert"
    - "Robots, on mountain"
    - "Stormtroopers in the park, Van Gogh style"
    - "Iron man in Antarctica"
  video_length: 32
  width: 512
  height: 512
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: False
  num_inv_steps: 50
  dataset_set: "val"


train_batch_size: 1
validation_steps: 100

resume_from_checkpoint: /mnt/disk_1/dongxin/FollowYourPose-main/checkpoints/followyourpose_checkpoint-1000


seed: 33
mixed_precision: 'no'
gradient_checkpointing: False
enable_xformers_memory_efficient_attention: True
